### ISSUE TITLE
Enable self-hosted registration on remote development environments

### ISSUE THREAD

**Issue by taiyosogawa** [MicrosoftDocs/vscodespaces#116]
Ability to register environment while connected to SSH, WSL, Containers, etc.

Inspired by #32, #113

**Comment by joecot** [comment]
For me personally, the ability to use the SSH Remote extension with a local environment (my desktop) would be preferable to trying to register my remote environment. My SSH environment uses an SSH key, a one time pass, and is IP protected. It'd be much easier to just have access to my desktop's VSCode config through VS Online

**Comment by scycer** [comment]
I would also like to be able to register a remote environment without a UI. The ability to simple click a environment and have the connection, ip, port forward etc all handled is awesome! I just want to use it with my existing environments.

Is this possible at all via commandline? Because it seems these instructions could surely correlate to a commandline equivalent: https://docs.microsoft.com/en-us/visualstudio/online/how-to/vscode#self-hosted

**Comment by taiyosogawa** [comment]
@scycer, we don't have that feature yet, but there is a lot of interest in it, which we're tracking on #69.

**Comment by iaxat** [comment]
Has there been any update on this, when is this feature coming?

**Comment by 2percentsilk** [comment]
Given [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/) and self-hosted support will be retired on November 20, 2020, we are not scheduling further investment in this service and will be closing this issue. We encourage you to join the discussion on self-hosted support on [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/19), where we’ll be gathering feedback to help inform our roadmap.

Thank you for participating in our public preview and providing this feedback.
