### ISSUE TITLE
Allow SSH connections to workspace VMs

### ISSUE THREAD

**Issue by carterbryden** [MicrosoftDocs/vscodespaces#177]
This would allow for tools like DB workbenches to integrate seamlessly with VSO the same way they would locally.

**Comment by lostintangent** [comment]
We're making improvements to our port forwarding service, that would allow forwarding arbitrary TCP services, that could then be accessible from external tools. Do you think that would be sufficient? That should enable the exact scenarios you mentioned, without requiring you to worry about SSH access at all.

**Comment by lostintangent** [comment]
@chuxel Do we have a doc we could point folks at that discusses how to get started with SSH + VS Code?

**Comment by Chuxel** [comment]
https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/sshd.md

For default codespaces image, people can jump to step 4 in "Usage in a Dockerfile" since its now in the image.

In short for it:

1. The first time you've started the container / codespace, you will want to set a password for your user (assuming you didn't set it using the script).

    ```bash
    sudo passwd $(whoami)
    ```

2. Connect to the container or [codespace using VS Code](https://docs.github.com/en/github/developing-online-with-codespaces/connecting-to-your-codespace-from-visual-studio-code). You can now SSH into the container on port `2222`. For example, if you are in the container as the `vscode` user, run the following command in a **local terminal**:

    ```bash
    ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vscode@localhost
    ```

    The “-o” arguments are optional, but will prevent you from getting warnings or errors about known hosts when you do this from multiple containers/codespaces.

**Comment by lostintangent** [comment]
@chuxel Thanks! Does the base image automatically run this image now? Or simply include it? Either way, I’m going to close this as resolved per the aforementioned docs.

**Comment by Chuxel** [comment]
@lostintangent I don't believe it forwards 2222 - unfortunatley it doesn't use a devcontainer.json last I checked.  This could be added into the what is in the kitchen sink docs.
