### ISSUE TITLE
400 bad request while connecting to environment

### ISSUE THREAD

**Issue by kumarz** [MicrosoftDocs/vscodespaces#189]
Unable to connect to an environment

seeing js error related to clientAuth  as shown below and getting 400 bad request.

**Note**: This issue is not occurring with clearing the cache/ opening in incognito mode

**Comment by jkeech** [comment]
@kumarz, can you provide more details or repro steps?

**Comment by plisy** [comment]
It looks like the service worker gets stuck under some conditions and refuses to send the requests through.

I've seen it a few times already, but don't see any errors from the worker or network or server. Once you clear site data or try incognito mode, things seem to work again and you can enter.

**Comment by legomushroom** [comment]
`Current solution:` clean the MSAL related cookies for that domain.
`Longer-term:` we will deploy a fix.

----

OK spend an evening with @fara-nak on this and now we have a good idea about what happens there. Drum roll.. `-> Cookie limits <-`.

We enable cookies for MSAL.js library which uses them to track the authentication requests it makes to AAD but the library never cleans up after itself. After there are enough cookies set(usually about 100 bytes each per cookie, about 20 cookies), we put the last straw on the camels back - we set the big(more than 1.2kb) `vso-pf` cookie.

Of course, browser behavior is bizarre. Officially there are no cookie limits in Chrome(mium), but in these circumstances, the browser flips off on its back and can never get on the feet again without users' help(and selection of the error `400` is unfortunate). Hence there should be about 6-8kb limit in reality. More interestingly, if you set a huge single cookie, it will show you another error - `431`, which might be expected since the cookie exceeds the HTTP request header limit.

We have a solution in mind that @fara-nak is testing right now that implies disabling the cookie option for the MSAL, since it is useless anyway. After we sure that the fix works, we can ship and deploy the patch. Alternatively, we can make change to MSAL(or make an issue for MSAL) to clean up those cookies.

This issue should be reported to Chromium repo since that, not the browser behavior they intended.

**Comment by lostintangent** [comment]
Closing this as resolved, since we've made _many_ changes to our auth system over the last year. @legomushroom please re-open this if we're still tracking an issue here. Thanks!
