### ISSUE TITLE
Anyway to backup the dev environment

### ISSUE THREAD

**Issue by williamwxz** [MicrosoftDocs/vscodespaces#221]
If the user accidentally delete the environment, is it anyway he/she can recover it?

**Comment by nikmd23** [comment]
Hi @williamwxz!

I hope you are asking hypothetically, and not because you've accidentally just lost data! 😧

We do not currently offer the ability to restore deleted environments.

Today, we'd recommend that users `git push` their changes to avoid losing workspace state. We're also looking at adding warnings that would tell users about uncommitted changes (#168) to help avoid workspace data loss.

Would you mind telling me more about the motivation behind this request?

**Comment by williamwxz** [comment]
Thanks for your reply! When I click delete the environment, it looks like the environment will be gone immediately, and hope there will be more warnings like "please enter the name of the environment" to delete it.

**Comment by lostintangent** [comment]
When you go to delete a Codespace, we now warn you if it had uncommitted changes in it. We've found this to be an effective means for preventing data loss, and so I'm going to close this issue as resolved. Please re-open it if you think we should consider adding more mechanisms for preventing data loss. Thanks!
