### ISSUE TITLE
Support Azure Managed Service Identity (MSI)

### ISSUE THREAD

**Issue by eisber** [MicrosoftDocs/vscodespaces#226]
Is it possible to get the [MSI](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) to run by default on the VMs?

**Comment by jkeech** [comment]
What is the scenario you want to enable? Today MSI, or specifically the IMDS service in Azure that enables MSI, is disabled in cloud-hosted environments since VS Online is a fully managed service in Azure in Microsoft-owned subscriptions. The MSI identities would therefore be tied to Microsoft's AAD tenants and would not be usable in external customer subscriptions.

**Comment by eisber** [comment]
From a user experience I'm logging in with my AAD credentials, so I'd like to use the same identity (just as I can on Azure notebooks) to access azure resources w/o having to re-authenticate.

**Comment by jkeech** [comment]
Just to clarify, you just want your user identity roamed and signed into the Azure extension and Azure CLI in the environment? If so, we do plan to support that via #231. I believe that's a different scenario than MSI though.

In the Azure Notebooks case, it looks like you can use MSI because you bring your own machines in your own subscriptions and connect them to the notebooks service. That's the equivalent in VSO of running your own Azure VM and setting up a self-hosted agent on that machine. In that case, IMDS and MSI would work. But if you run on the managed environments/compute in the Microsoft-owned subscriptions (no underlying compute resources in your subscription), then MSI wouldn't work.

**Comment by lostintangent** [comment]
Now that we're consolidating Codespaces into GitHub Codespaces, I'm going to close this as won't fix, since it no longer makes sense as part of a GitHub-native service. Please re-open this if I misunderstood the request, or if you want to continue discussing an enhancement here. Thanks!
