### ISSUE TITLE
Don't automatically run npm install or build after creating a new environment

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vscodespaces#25]
**Repo**
1. Set up a new environment for `vsls-contrib/guestbook`
1. Connect and wait around for a while while the `VS Online` terminal is doing stuff 
1. Notice it is automatically running `npm install` and doing a build

**Expected**
Creating a new environment should only `git clone`. Kicking off installs and builds automatically is unexpected, can take a really long time and surface confusing errors, and means I have to trust the repo I am working with before I can even inspect it

**Comment by jkeech** [comment]
This is currently by design, and only happens when you don't specificy a `postCreateCommand` in devcontainer.json. VS Online tries to give smart defaults without requiring a lot of config so that you can get to productivity as fast as possible when creating and using a VS Online environment. Environmetns automatically run [Oryx](https://github.com/microsoft/Oryx) build to detect the language and auto install dependent packages. All of this runs asynchronously in the background, so it doesn't slow down environment creation or prevent you from connecting as soon as possible. If you connect while Oryx is still running, you can track the status of the restore/build in the VS Online terminal window.

If you want to opt-out of the oryx build or run custom logic on environment creation, you can specify a `postCreateCommand` in devcontainer.json and that will be honored.

**Comment by mjbvz** [comment]
I am really not a fan of this design. Right now, the majority of repos are not going to have dev containers and it feels very intrusive that this stuff just happens when I simply create and connect to a new environment. New environment for me should simply be a `git clone`

This behavior can also create a confusing first run experiences since all the install and build info (including potential errors) ends up getting printed to the VSO output terminal. The only reason I even realized VSO was doing this was that I saw a scary looking error printed from a failure that happened during the automated build

**Comment by connorshea** [comment]
For what it's worth, I also really dislike this behavior. It shouldn't do anything besides the clone. My Rails app uses Yarn, so doing `npm install` can mess with things.

**Comment by jkeech** [comment]
@connorshea, are you seeing it run `npm install` when you use yarn, or are you just saying that if it ran `npm install` you wouldn't be happy? If it kicked off a `yarn install` instead, would your opinion switch? Oyrx is supposed to distinguish between npm and yarn and [invoke the correct install command](https://github.com/microsoft/Oryx/blob/9fffedac953b95d0270534bbec4f124782b8ede7/src/BuildScriptGenerator/Node/NodePlatform.cs#L75).

**Comment by nikmd23** [comment]
FWIW, I wanted to let everyone know you can currently opt out of this behavior if you have access to the repository you're creating an environment from. To do so, add a [devcontainer](https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring) with the following:

```js
/* Contents of {repository-root}/.devcontainer/devcontainer.json */
{
  // Opt-out of default behavior:
  "postCreateCommand": "",
}
```

**Comment by tclzcja** [comment]
Maybe simply add a section to define postCreateCommand while creating the environment on the web? There you can put a default "npm install" value in the input, just like the current default value for Environment Name and Repo. By doing that, ppl can be 100% noticed that there IS a pre-defined postCreateCommand, and they have the freedom to remove it.

Of course you can still modify the postCreateCommand in .devcontainer.json.

**Comment by jkeech** [comment]
@tclzcja, the `oryx build` logic is more complicated than just `npm install`. It changes dyamically based on the inferred languages in the repo, so it requires a clone of the sources to analyze, which doesn't happen until after the environment is created. I don't think it's feasible to run all of those steps prior to creating the environment. The closest equivalent would instead be filling in `oryx build` as the default postInstallCommand, which is effectively what it is doing today.

**Comment by mchelen** [comment]
I agree that this can produce some surprising results. For example, our Readme specifies using `npm ci` but I'm not sure if VSOnline/Oryx will try to run `npm ci` or `npm install`? It seems like an "initialize dependencies" checkbox when creating a new environment would help users be aware of this, even if it's checked by default.

**Comment by jkeech** [comment]
@mchelen, I believe it will just run `npm install`. I like the idea of having a checkbox to enable/disable this feature.

**Comment by lostintangent** [comment]
Closing this for now, since we're consolidating feedback towards the [GitHub Support Community](https://github.community/c/codespaces-beta/45), we haven't heard much interest in this change from customers, and you can already "workaround" this by defining your own custom `Dockerfile`. If folks would still like us to consider this change, please let us know by filing an issue in the linked GitHub forum. Thanks!
