### ISSUE TITLE
Recommended credential config for HTTPS Git?

### ISSUE THREAD

**Issue by mchelen** [MicrosoftDocs/vscodespaces#298]
Hello,
Is there a recommended approach to configure VS Online (in browser) to store Git credentials for use with HTTPS repo urls? Right now I'm getting a username/password prompt on every push or pull.

Does the credential helper suggestion here: https://code.visualstudio.com/Docs/editor/versioncontrol#_remotes apply to VS Online as well?

Thanks

**Comment by nikmd23** [comment]
Hi @mchelen! This should not be the case. Are you seeing this on all environments you create, or one in particular? Are you using a self-hosted or cloud-hosted environment?

**Comment by lostintangent** [comment]
@edgonmsft Do we have any known issues with our credential providers?

**Comment by edgonmsft** [comment]
The only know issue right now is if you connect from multiple places at the same time, for example VS Code desktop and web, the credential proxy might not go to the correct one and fail. 

Also there should not be a credential prompt in the environment since we disable that with our credential helper. If its prompting its possible the configuration is missing or was removed in some way.

**Comment by lostintangent** [comment]
We've made quite a few changes to our git credential helper over the last few months, and so I'm going to close this as resolved. However, if you're still running into any issues, please re-open this and we'll investigate it. Thanks!
