### ISSUE TITLE
Ensure the environment is fully prepared before allowing users to connect to it

### ISSUE THREAD

**Issue by Naninani** [MicrosoftDocs/vscodespaces#349]
When creating a new workspace with a large rpo (ours is over 7GB), almost all files are marked as deleted.
It takes couple of min and a refresh of the workspace to fix that.
This could be confusing at 1st for new users.

**Comment by jkeech** [comment]
I agree this is confusing. We currently allow connecting to the environment before it is fully setup. Clone and restore happens async. So you can connect before the clone finishes.

In this case, it sounds like the Git extension in VS Code ran a `git status` while the clone/checkout was happening in the background, which made it look like the files were deleted, because they hadn't been checked out yet.

We will be making some changes in the future to clone the repo onto the host prior to starting the container, and then bind-mounting the source folder into the container. In this case, the repo will be pre-cloned prior to connecting to the environment (although potentially a bit longer startup times), which should reduce confusion. It will also make things like VS Code extensions/settings specified in  `devcontainer.json` able to be picked up immediately instead of after a refresh since VS Code in the web doesn't currently support hot-reload of newly installed extensions.

**Comment by lostintangent** [comment]
This should now be resolved, since we clone the repo on the host VM and don't navigate users into the editor until it's finished. Let us know if you're still running into any issues. Thanks!
