### ISSUE TITLE
Extend the "deep link" endpoint to accept files to seed the environment with

### ISSUE THREAD

**Issue by orta** [MicrosoftDocs/vscodespaces#37]
I'd love to be able to let folks export from the TypeScript playground to a vsonline environment. We currently do it for code sandbox and stackblitz https://github.com/orta/typescript-play/pull/30

This could either be through a GET to a url, which is limiting ( ~500 chars are allowed in a URL ) or a POST which returns a place I can redirect a user to.

**Comment by RichiCoder1** [comment]
This would also be great for internal getting started's and doing things like links on pull requests to spin up review environments.

**Comment by jkeech** [comment]
We have a way for you to construct a url with some template parameters for environment creation filled in, and then anyone who clicks on the link will enter into the environment creation wizard with all of the details filled in, they just have to confirm the create.

Unfortunately I don't think we have this documented yet, but we can get docs written soon (/cc @nikmd23). Here's an example link where you can see the query params are the template values: https://online.visualstudio.com/environments/new?name=conduit_issue_10&repo=https://github.com/lostintangent/Conduit

**Comment by nikmd23** [comment]
I'll get the docs written ASAP. Until then, also take a look at https://github.com/nikmd23/ballpark-tracker/blob/master/README.md for another example of a similar button.

**Comment by lostintangent** [comment]
I don't believe our current deep link URL is sufficient for this scenario, since the TypeScript Playground needs to be able to migrate files to the environment. So this is semi-related to #205, where we need to allow environments to be created from a set of files, as opposed to a Git repo.

After addressing #205, we'd then need to extend our deep link URL to allow it to accept file contents (potentially via a `POST`), in addition to the existing parameters it accepts (e.g. name, instance type, etc.). I'm going to re-purpose this issue to track this specific change, as a compliment to #205.

**Comment by lemmy** [comment]
Do you have documentation for the query strings from which one can build an url?  The current example shows "name" and "repo", but is it possible to also set instance type, idle timeout, ...?

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so this experience is something that we'd need to add to github.com, as opposed to the online.visualstudio.com portal. If this is something folks would like to see, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
