### ISSUE TITLE
Unable to install VSOnline CLI on Linux ARM platform

### ISSUE THREAD

**Issue by wazybr** [MicrosoftDocs/vscodespaces#395]
Hi!
I'm unable to install the recently released CLI version of VSO on my Raspberry Pi 3B+ running Raspbian (Debian) 9.4 stretch.
The `vso` package is not available when searching on apt. And using the script located at https://aka.ms/install-vso-linux says that VSO was installed succesfully, but when trying to run I get this error:

```
-bash: /usr/bin/vso: cannot execute binary file: Exec format error
```

Possibly the script downloaded i386 or amd64 binaries. Isn't there an ARM version available? Sorry if this is pointed somewhere in the docs. I could have missed something.

**Comment by jimbobbennett** [comment]
+1 to this - would love Raspberry Pi support. More and more adults kids are making and learning from home using Pis, so it would be great to support this platform with Code, both as an app and the online experience.

**Comment by reaktivo** [comment]
Is there any official response to this? Has anybody found a workaround to have this working on RPis?

**Comment by wazybr** [comment]
Any updates on this? At least the install script should check the platform and cancel installation if it's not supported.

**Comment by Rathna-K** [comment]
@Davsterl will this be compiled for rmhf / raspbian? is there a roadmap or timeline for this feature? thank you

**Comment by thilux** [comment]
+1 This would be a fantastic feature to be able to run it on a raspberry pi or any arm arch for that matter.

**Comment by 2percentsilk** [comment]
As part of the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will need to be migrated to GitHub Codespaces. Since this migration isn't part of our roadmap and the self-hosted service will be retired on November 20, 2020, I'm going to close this as won't fix as we are not investing in this CLI anymore.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
