### ISSUE TITLE
Self-hosted connection failure

### ISSUE THREAD

**Issue by taiyosogawa** [MicrosoftDocs/vscodespaces#408]
See https://twitter.com/jcouv/status/1249929734865047553?s=09 for context

Julien, I've got a few questions to get us started diagnosing the issue:
1) Could you let us know the OS of the host machine (that you're connecting to)?
2) Did you register as a process or as a service/daemon?
3) Do you see a process with the name 'vso' running on the host machine?

**Comment by jcouv** [comment]
1. the host for remote is running Win10 10.0.18363 Build 18363
2. I registered as a process
3. no, I don't see any process named `vso`

Shared my zipped log files at `"\\jcouvdev\shared-dumps\VSFeedbackVSRTCLogs.zip"

FWIW, here's the environment I'm trying to use: https://online.visualstudio.com/environment/f5883224-e96c-4fe2-afee-8ab1517dc01b?folder=%2Fd%3A%2Frepos%2Froslyn%2Fsrc

The IDE extension shows the environment as properly registered:
![image](https://user-images.githubusercontent.com/12466233/79391671-d1966280-7f26-11ea-9c4c-8cc7f2d3d6d3.png)

**Comment by taiyosogawa** [comment]
@jcouv, thanks for sending the logs over. Could you try deleting your `%UserProfile%\.vscode-remote` directory and trying again? When you connect, the host agent tries to download dependencies to that folder and it looks like permission was denied. 

That directory might be used by other applications - we are moving ours soon to avoid such conflicts.

**Comment by 2percentsilk** [comment]
Closing this item due to lack of activity.

Please note: As part of the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will need to be migrated to GitHub Codespaces. Since this migration isn't part of our current roadmap, the self-hosted offering will be retired on November 20, 2020.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
