### ISSUE TITLE
You have exceeded the environment quota

### ISSUE THREAD

**Issue by jordanbean1** [MicrosoftDocs/vscodespaces#426]
Why was the quota limit lowered so dramatically? The previous limits allowed my whole team to use VSO and to have several environments each (one for each repo they commonly use). The new limits force us to have 1 environment for each team member (and ensure our team never grows larger than 6) and they will have to clone all the repos they use into 1 environment.

**Comment by abuchholtzau** [comment]
As our service matures, we are trying to align to Azure standards and so our quota was updated to more closely match the quotas for VMs in Azure. 

We are currently working on native integration with the Azure quota system to allow you to request increases from within the Azure portal, as well as updating the quotas to focus on more meaningful measures, such as limiting simultaneously running environments instead of total environments. 

We understand the current quotas have disrupted your workflow but hope that our coming improvements will help alleviate that in the future. Thanks for your feedback.

**Comment by jordanbean1** [comment]
Could you be more specific about the phrase "match quotas for VMs in Azure".

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#virtual-machines-limits---azure-resource-manager

**Comment by lostintangent** [comment]
Closing this as won't fix, since we're consolidating Codespaces into GitHub (per #788), and so the quota management will be handled from the GitHub side. If folks have any feedback on the quotas for GitHub Codespaces, please let us know via the [Community Support](https://github.community/c/codespaces-beta/45) forum. Thanks!
