### ISSUE TITLE
inconsistency in vs-online/how-to/self-hosting-vscode.md

### ISSUE THREAD

**Issue by omartin2010** [MicrosoftDocs/vscodespaces#439]
In trying out the feature documented [here](https://docs.microsoft.com/en-us/visualstudio/online/how-to/self-hosting-vscode), I'm hitting some inconsistencies with the UI presented in the article. My vscode (
```
Version: 1.45.0-insider (user setup)
Commit: abb4a35cfc26102f93fd00df7b59ce1a19c2017a
Date: 2020-04-28T05:36:25.810Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
)
won't render the remote icon below the extensions icon, and I'm able to access it using the command palette... not sure if docs need to be updated or not. Then once this is done, I see it under the remote icon where I normally do remote SSH/Containers. But before I did the connection to VSO, I wasn't seeing it in the remotes section. Perhaps all this should be integrated in the default VS Remote options?

**Comment by omartin2010** [comment]
To add a precision, this inconsistency seems to be present in vscode insider, but not in the release of vscode non insider (release : 
```
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
)

**Comment by 2percentsilk** [comment]
I'm going to close this due to inactivity / not repro.

Thanks for your feedback. As a note, due to the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will need to be migrated to GitHub Codespaces. Currently, this migration isn't part of our roadmap and the self-hosted service will be retired on November 20, 2020.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
