### ISSUE TITLE
Feature Request: Option to disable SSO

### ISSUE THREAD

**Issue by JtMotoX** [MicrosoftDocs/vscodespaces#451]
I use Azure DevOps and O365 using my Microsoft account provided by my company.  I am using VSO with my personal account.  I am able open my browser and log into VSO using my personal account.  When I log into Azure DevOps using my company account, it signs me out of VSO and I am not able to sign back in.

Is it possible to be signed into Azure DevOps, O365, etc.. using one account and then use another account for VSO?

**Comment by lostintangent** [comment]
Closing this as won't fix, since we're in the process of consolidating Codespaces into [GitHub Codespaces](https://github.com/features/codespaces), and therefore, aren't making any changes to the auth support for VSO. If possible, we'd recommend signing up for GitHub Codespaces and starting to move your development to that. Thanks!
