### ISSUE TITLE
Multiple windows, one code space

### ISSUE THREAD

**Issue by mmeyer724** [MicrosoftDocs/vscodespaces#462]
Hi there,

Is there any way to have multiple windows connected to the same codespace? or possibly multiple 'codespaces' hosted from the same machine? 

I often work on multiple projects at once, and I like to have a separate windows for each one because it helps keep me organized. I can't seem to find a way to do this with vsonline / codespaces. 

Unfortunately I cannot create individual codespaces because these projects need to be able to communicate with each other (they're microservices). 

I'm using Visual Studio Codespaces (running on Azure) with a local VS Code installation.

Best,
Michael

**Comment by abuchholtzau** [comment]
You can technically do this now but it requires a bit of a workaround since you can't have two connection to the same workspace. 
When you make the first connection with the Codespace, close the open folder and then reopen the specific folder for the microservice you want. Then you can open another instance of VS Code and connect to the same Codespace (since you're now connecting to a different workspace within that environment.) Follow this process until you have the connection you need. 

We're working on a feature right now that lets you directly connect to a specific folder in the Codespace and we hope it have it shipped soon, which should make this easier for you!

**Comment by mmeyer724** [comment]
Thanks @abuchholtzau! Connecting to a specific folder in a codespace is exactly what I want. In the meantime, I'll try out the workaround. :)

**Comment by abuchholtzau** [comment]
Let me know if you run into any issues! We're happy to help :)

**Comment by lostintangent** [comment]
Closing this as resolved, per the aforementioned workaround. Please reopen it if you’re running into any issues. Thanks!
