### ISSUE TITLE
Need a way to set vm.max_map_count

### ISSUE THREAD

**Issue by tashbaugh** [MicrosoftDocs/vscodespaces#486]
Trying to leverage codespaces as my full time development environment. A project that I'm working on uses Lando for local dev. While attempting to install Lando in my codespace I'm getting an exception when it tries to set vm.max_map_count to a high enough value to satisfy ElasticSearch. 

Is there a way I can modify this kernel level value?

`Setting up lando (3.0.0) ...
LANDO_ROOT=/usr/share/lando
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/opt/oryx:/opt/nodejs/lts/bin:/opt/python/latest/bin:/opt/yarn/stable/bin:/usr/local/bin
TERM=xterm
chmod 755 -R /usr/share/lando
mkdir -p /usr/local/bin
ln -sf /usr/share/lando/bin/lando /usr/local/bin/lando
awk -F: '$1 == "sudo" {print $4}' /etc/group
SUDOERS=
'[' -f /proc/sys/vm/max_map_count ']'
sysctl -w vm.max_map_count=262144
sysctl: setting key "vm.max_map_count": Read-only file system
dpkg: error processing package lando (--install):
 subprocess installed post-installation script returned error exit status 255
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 lando`

**Comment by tashbaugh** [comment]
Just an update here, ElasticSearch recommends updating the setting in the /etc/sysctl.conf file as [referenced here](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html#vm-max-map-count) however this does not apply from inside the container. Still looking for options on how to satisfy this requirement of ElasticSearch when leveraging Codespaces as a development environment.

**Comment by jkeech** [comment]
I don't think this is currently possible, but we are making some changes soon that will enable this. I would expect it to work as follows:

1) Use a custom container via `devcontainer.json`
2) In the `devcontainer.json` specify a custom mount that mounts `/etc/sysctl.conf` on the host into `/etc/sysctl.conf` inside the container
3) You should then be able to update the file within the container which will update it on the host

In order to do step (2), we need #459 to be deployed where we will honor any mounts specified in the `devcontainer.json`

**Comment by jkeech** [comment]
One thing that would be problematic though is that since the file would be bind-mounted from the host, the changes would not be persistent across suspend + resume. You would potentially need to re-run the command after resuming since you will be on a fresh host.

@chuxel, this is another use case where we might need some sort of `resumeCommand` in `devcontainer.json`. Any scenarios in Codespaces that needs to modify config on the host outside of the container will not be persisted across suspend + resume.

**Comment by Chuxel** [comment]
Yes I agree. @chrmarti Is looking at `postStartCommand` and `postAttachCommand` this iteration for Remote - Containers.  Anything you want to happen whenever the containers starts (create or resume) can go in the first. https://github.com/microsoft/vscode-remote-release/issues/2772

I believe its in insiders now.

**Comment by chrmarti** [comment]
(Not in insiders yet. I plan on publishing a new version next week.)

**Comment by lostintangent** [comment]
Closing this as resolved since #459 was addressed, and we're also tracking support for `postStartCommand` separately.

 @jkeech please re-open this if I misunderstood the requirements here. Thanks!
