### ISSUE TITLE
Keyboard shortcuts are not persistent between sessions (when using InPrivate)

### ISSUE THREAD

**Issue by sumitsumit** [MicrosoftDocs/vscodespaces#492]
_[reposting here, as suggested by bpasero]_

I love codespaces, but am finding the keyboard shortcuts are not preserved between sessions when using an InPrivate window. The setting file's path is reported as /User/keybindings.json, but this doesn't exist in the container. For now I'm saving a copy in .vscode and then copying it over when the bindings disappear. I'm using an in-private window for codespaces, as otherwise it gets very confused between my personal and organization microsoft accounts (separate issue). However, in any case I (and I expect others) would want to use my codespaces from a variety of machines/browsers, so there's a need for preserving customizations across sessions.

**Comment by jkeech** [comment]
Hi @sumitsumit, glad to hear that you are enjoying Codespaces for the most part.

Certain pieces of user data are actually stored on the client side in the browser, including user keybindings, settings, etc. That's why you don't see them on disk in the container. If you open F12 tools -> Application -> IndexedDB, you will actually see the files and their contents stored there.

What is happening in this case is that since you are using an in-private browser session, the local storage and IndexedDB are getting cleared out between sessions, and therefore your keybindings changes are not persisted.

But I have good news! VS Code is working on a feature called [Preferences Sync](https://code.visualstudio.com/docs/editor/settings-sync) (also called Settings Sync), which is available in VS Code insiders today. Preferences Sync will keep your settings/keybindings/extension/etc in sync across all of your VS Code instances, both in the web and on the desktop, for any VS Code instance that is signed in an has Preferences Sync enabled. Eventually this will make it into VS Code stable, but for now it's only insiders.

You can switch to insiders in Codespaces by navigating back to the management portal, and clicking the top right corner, then click "Settings". Then turn on the Insiders channel toggle.
![image](https://user-images.githubusercontent.com/746020/81744606-4db59480-9458-11ea-9d2b-2bdc27753bcb.png)

For now you will have to re-sign into to Preferences Sync every time, but we will be turning it on by default soon using the identity that you use to sign in to the Codespace. Then your keybindings would automatically roam along with your extensions, settings, etc.

**Comment by sumitsumit** [comment]
Ah, very cool, I'll check that out!

**Comment by rlj1202** [comment]
Yes! This is exactly what I wanted for long time!

**Comment by lostintangent** [comment]
Closing this as resolved per the addition of settings sync. Please re-open this if you're continuing to encounter any problems. Thanks!
