### ISSUE TITLE
Cannot create new codespace in existing RG

### ISSUE THREAD

**Issue by dclayh** [MicrosoftDocs/vscodespaces#530]
We had a VS Online billing plan/codespace set up in a shared resource group. Recently (around the time of the codespaces rebrand), we have been unable to access either the existing codespace (or any environments within it), or create a new one, despite having full owner privileges to that RG. The error message is only "The resource validation failed."

**Comment by jkeech** [comment]
@dclayh, what action are you taking when you get that message? You could be running into subscription quota limits for the number of plans when creating new plans: https://docs.microsoft.com/en-us/visualstudio/online/resources/faq#what-are-visual-studio-codespacess-quotas

Today each plan is only usable by the person who created it originally, regardless of who can see it in the Azure portal. #146 is tracking the work to enable multiple users to share the same plan.

**Comment by dclayh** [comment]
The action for that message is clicking "create" on the "Create a billing plan" panel. 

I wasn't aware of these restrictions/quotas, that's very likely the issue then. Two followup questions:
1. Is it possible to see in the azure portal who created the plan?
2. Can we request changes to the default quotas through MS support?  This is a very large (enterprise) subscription, so only 2 plans would be very difficult.

**Comment by jkeech** [comment]
> 1. Is it possible to see in the azure portal who created the plan?

If the plan has been created in the past 90 days, you can look in the Activity Log for the plan, and look for the event when it was created. It will tell you who initiated the event. If it's older than 90 days, there's not a great way to check today.

> 2. Can we request changes to the default quotas through MS support? This is a very large (enterprise) subscription, so only 2 plans would be very difficult.

We are working on adding an easier way to do this by integrating with the Usage and Quotas section of the Subscriptions blade, but you could still reach out to support manually and request an increase. We are also working on switching the quotas to be based more on active Codespaces and active cores consumed instead of just the existence of Codespaces. But for larger teams, you'd still likely run into the default limits and would want to request an increase.

In general, the service is geared more towards individual developers today, but we are working on a lot of enterprise features to make it work great for enterprises too (including plan sharing, better Azure portal integration, quota changes and ability to easily request quota increases, VNET support, policies, etc).

**Comment by simondmorias** [comment]
@jkeech we too are seeing this error. Our subscription has 4 code spaces created - I assume all were created before the quota was applied. We reached out to support to raise the quota (ticket 120060224004452) - but they said they could not help because Codespaces is still in preview and suggested we raise an issue here.
How can quotas be raised?
Thanks

**Comment by jkeech** [comment]
@simondmorias, I'm following up via your support ticket. We should be able to resolve it there. Thanks!

**Comment by lostintangent** [comment]
Closing this since @jkeech mentioned the conversation was moved to a support ticket. Please re-open this if you're still encountering an issue. Thanks!
