### ISSUE TITLE
vso-cli fails by ErrorCode : Forbidden

### ISSUE THREAD

**Issue by TsuyoshiUshio** [MicrosoftDocs/vscodespaces#531]
According to this blog post, I tried vso cli. 

https://devblogs.microsoft.com/visualstudio/bring-your-own-machine-to-visual-studio-online/
I tried Windows and Linux. However, the result was the same.

## Execution Log
This execution log is on Windows 10 machine.  I logged in with MSFT subscription. 

```powershell
 vso start
[2020-05-21 21:35:23.542 CLI I] vso v1.0.2005.59801 (pid: 912)
[2020-05-21 21:35:23.817 CLI I] Authenticating...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AFE25FPN9 to authenticate.
Would you like to run as a persistent service/daemon? [Y/n]: n
[2020-05-21 21:37:42.679 CLI I] Will run as a process
[2020-05-21 21:37:43.404 CLI I] A VSO plan is required to register your environment.
[2020-05-21 21:37:43.407 CLI I] Using VSO plan: /subscriptions/{MY_SUBSCRIPTION_ID}/resourceGroups/vso-rg-6473390/providers/Microsoft.VSOnline/plans/vso-plan-westus2
Enter an environment name or blank to use [DESKTOP-SDE49UK]: tsushi-local
[2020-05-21 21:37:55.690 CLI I] Creating your environment...
[2020-05-21 21:37:57.416 CLI E] [!ERROR] Error calling HTTP POST at 'https://westus2.online.visualstudio.com/api/v1/environments' ErrorCode : Forbidden
```

## Version
```
> vso -v
[2020-05-21 22:12:17.855 CLI I] vso v1.0.2005.59801 (pid: 24352)
Command-line interface for Visual Studio Online
1.0.2005
```

**Comment by TsuyoshiUshio** [comment]
Self solved. I already had three code spaces projects.  I remove some of them. Then the Fobbiden was gone. I'm happy to close this issue, however, I keep it until some owner watch this issue to share the experience. Thanks.

**Comment by jkeech** [comment]
Thanks. There have been a couple other issues filed for the same problem. I think we need to have a better error message here. @Davsterl, do you want to use this issue to track the better user experience when users are registering the self-hosted Codespace and are at the limit?

**Comment by 2percentsilk** [comment]
I'm going to close this issue since we've made updates to how we're checking quota and we are not investing further in the self-hosted service and CLI. 

In case you didn't know, [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/) ands elf-hosted support is not currently included in GitHub Codespaces. As a result, self-hosted support will be retired on November 20, 2020. We encourage you to join the discussion on self-hosted support on [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/19), where we’ll be gathering feedback to help inform our roadmap.
