### ISSUE TITLE
Self Hosted: vso start as temporary process

### ISSUE THREAD

**Issue by GabbySF** [MicrosoftDocs/vscodespaces#537]
Hi,
I am trying to run a self hosted vso in wsl 2. It works fine by running it as temp process.
My question is how do I start the process again after I reboot my system?
What parameter I need to pass to vsls-agent on the following start up?

Thanks

**Comment by 2percentsilk** [comment]
Registering a local environment while connected to a remote server (WSL or SSH) is not supported.

As part of the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will need to be migrated to GitHub Codespaces. Since this migration isn't part of our roadmap and the self-hosted service will be retired on November 20, 2020, I'm going to close this as won't fix as we are not investing in this feature set anymore.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
