### ISSUE TITLE
VSO only starts if persistent service/daemon is set to no

### ISSUE THREAD

**Issue by accessTechnology** [MicrosoftDocs/vscodespaces#541]
If persistent service/daemon is set to yes, device always hangs on "Waiting for environment to become available."

**Comment by ljtill** [comment]
Also experiencing this behaviour (Ubuntu 20.04).

**Comment by gro1m** [comment]
#https://github.com/MicrosoftDocs/vsonline/issues/453

**Comment by 2percentsilk** [comment]
As part of the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will need to be migrated to GitHub Codespaces. Since this migration isn't part of our roadmap and the self-hosted service will be retired on November 20, 2020, I'm going to close this as won't fix as we are not investing in this CLI anymore.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
