### ISSUE TITLE
Running self-hosted environment within a Docker: possible at all? 

### ISSUE THREAD

**Issue by kovla** [MicrosoftDocs/vscodespaces#587]
Hi,

I am trying to set up a self-hosted environment, where `vso start` is run within a Docker container. Two problems occur: 

### Problem 1: 
One issue that emerges is that vso agent freezes during the following step: 

```
Would you like us to run 'loginctl enable-linger' to enable services to run even when you're not logged on? [Y/n]:y
Running 'loginctl enable-linger'... failure
Warning: self-hosted environment will be unavailable while logged off unless you run 'loginctl enable-linger'
[2020-06-16 08:00:54.730 CLI I] Waiting for environment to become available...
```
Nothing further happens, status at `https://online.visualstudio.com/environments` for this environment is stuck on "Creating...". 

### Problem 2: 
Aside from this, it seems that I have to manually authenticate by going to `https://microsoft.com/devicelogin` and entering a code. In reality, the Docker container running vso will not be available to users, so they would not see the code. Is there an alternative method to authenticate a vso agent? 

Thanks!

**Comment by 2percentsilk** [comment]
Currently this isn't possible. 

I'm going to close this issue since we are not investing further in the self-hosted service. In case you didn't know, [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/) ands elf-hosted support is not currently included in GitHub Codespaces. As a result, self-hosted support will be retired on November 20, 2020. We encourage you to join the discussion on self-hosted support on [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/19), where we’ll be gathering feedback to help inform our roadmap.

Thank you for participating in our public preview and providing this feedback!
