### ISSUE TITLE
Self hosted + containerized development environments

### ISSUE THREAD

**Issue by sharif1093** [MicrosoftDocs/vscodespaces#590]
Probably related to #287.
I wonder how I can use self-hosted environments with containers. VSO does not let us install "Remote - Containers" extension. Also, running VSO from inside a container seems not working; it complains about not being able to connect to the client (#587).
I know that `devcontainer.json` addresses this issue for cloud-hosted vso instances. But not sure if the same solution should be used for self-hosted environments (tried it and it seemed to ignore `devcontainer.json`).

My use case is that my remote workstation has good hardware resources which I want to use; however, I still want to use containers for controlling the development environment.

**Comment by MichalCz** [comment]
Self hosted option just doesn't seem to work at all for me now.

I have a docker container and a script that creates a docker env for vs-code and uses remote servers, but that on the other hand requires some tweaking in docs.

**Comment by 2percentsilk** [comment]
Hi there.

Currently this isn't possible and I'm going to close this issue since we are not investing further in the self-hosted service. In case you didn't know, [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/) ands elf-hosted support is not currently included in GitHub Codespaces. As a result, self-hosted support will be retired on November 20, 2020. We encourage you to join the discussion on self-hosted support on [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/19), where we’ll be gathering feedback to help inform our roadmap.

Thank you for participating in our public preview and providing this feedback!
