### ISSUE TITLE
Disappearance of projects.

### ISSUE THREAD

**Issue by lucusapp** [MicrosoftDocs/vscodespaces#602]
Hi. I had five projects hosted in visual studio code to do programming tests. Yesterday I have been working on them. However, when accessing my account today I have seen that none of the projects appear, which generates anguish since I had not supported them on github. Could you please help me? Thank you. My developer account is gavialus@hotmail.com

**Comment by abuchholtzau** [comment]
Hi there.
A couple clarification questions:
Where are you trying to access these projects, is this through the online.visualstudio.com portal or from the Codespaces extentsion in VS Code? 
Were they in a single Codespace or one project per Codespace?

**Comment by lucusapp** [comment]
Thanks for the reply. The projects were available by accessing the
visual studio online platform. Now it indicates to me that there is no
project available. Yes. However I have not removed any project.

**Comment by abuchholtzau** [comment]
So when you login to online.visualstudio.com, you don't see any Codespaces to connect to?
Are they possibly in a different plan?

**Comment by lucusapp** [comment]
I connect regularly, however my projects have disappeared. In the plan
of Europe there were 5 projects, but you indicated that there is none.
This should have happened the morning of Friday to Saturday as I was
working on Friday afternoon, however they were no longer on Saturday
morning.

**Comment by osortega** [comment]
Hello @lucusapp 
Unfortunately looks like the plans you used to create those Codespaces were under a Free Trial subscription that expired or got deleted. What happened was that the Codespaces associated and billed against that subscription got deleted with it as well.

I'm really sorry that this happened.

**Comment by lucusapp** [comment]
Hi. I am quite disgusted with what happened. There should be a notice
that the repositories are under a trial license and that they will be
removed in order to save the work being done or subscribe to a plan.
In this sense, the platform is disappointing.

**Comment by abuchholtzau** [comment]
We're really sorry this happened. We're working on improvements to the platform that should help alleviate this problem in the future.

However, the auto-deletion of resources after a Free Trial expires is due to the way Azure handles the Free Trial. I encourage you submit feedback directly to the Azure team on their [feedback site](https://feedback.azure.com/forums/34192--general-feedback).
This item looks similar to your concern: [Warn before deleting a Free Trial](https://feedback.azure.com/forums/34192--general-feedback/suggestions/40059064-please-give-more-warning-in-relation-to-cancelling).

**Comment by lostintangent** [comment]
Closing this as resolved, since this is a request on the way that Azure handles free trial subscriptions. Apologies again for the disappointing experience.
