### ISSUE TITLE
Some clarity on the network model for self-hosting?

### ISSUE THREAD

**Issue by joewood** [MicrosoftDocs/vscodespaces#610]
I couldn't find this information in the documentation, I was wondering what the network model is for self-hosting.

Is the relay server an active proxy, routing all traffic between VS Online and the server? Or is the relay just a directory service for authentication, so traffic is routed directly to the server within the corporate network?

I suspect the model is for the former. Is there a document explain this?

**Comment by 2percentsilk** [comment]
Hi @joewood, there is not a document that explains this - although you've basically got it right in that we work through a relay to connect you to any of your codespaces. I'm going to close since we've now answered your question (albeit a bit late).

As a note, due to the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will need to be migrated to GitHub Codespaces. Since this migration isn't part of our roadmap and the self-hosted service is set to be retired on November 20, 2020, we are not investing in this area at this time.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
