### ISSUE TITLE
[Selfed Hosted] Many pipe tasks are created

### ISSUE THREAD

**Issue by soilSpoon** [MicrosoftDocs/vscodespaces#655]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9105017/87397737-c3241980-c5ef-11ea-9452-c0d6874db1d4.gif)

Same as above

vsls-agent too many created
use many memory and use many cpu

OS: Ubuntu 20.04 (x86_64)
VSO Version: v1.0.2453.1726

**Comment by ckaczor** [comment]
I'm battling the same issue - eventually so many vsls-agent processes spawn that things start running out of memory.

**Comment by danyhoron** [comment]
I also noticed that on MacOS too.
I also encountered another issue, after a while, my mac would stop opening apps or run terminal commands, throwing: `too many open files` error.

**Comment by ckaczor** [comment]
I switched to Ubuntu 18.04 Server and it doesn't create a lot of processes like it did with Ubuntu 20.04 server but the codespace only works for a little bit before becoming unavailable.  If I don't try to run it as a service (just using "vso start") then it seems to work okay - everything has been good for a few days.

It is a bit of a pain if I restart the machine since I have to do a "vso stop" and then "vso start" to get things going again but I don't restart it very often so it isn't a big deal right now.

**Comment by Dr-Danimal** [comment]
I'm running onto the same issue on Ubunu Server 20.04

**Comment by lorenpaulsen** [comment]
Just following up to report that this issue has been fixed.
