### ISSUE TITLE
[Self hosted] Flag to answer "continue as root" question

### ISSUE THREAD

**Issue by TylerLeonhardt** [MicrosoftDocs/vscodespaces#656]
If you run `vso start` with a user who is root (like inside of a Docker container for example) you are prompted with:

```
[2020-07-14 17:50:26.608 CLI I] Running vso start as root is not recommended: https://aka.ms/vso-self-hosted
[2020-07-14 17:50:26.608 CLI I] Would you like to continue as root? [y]/[N]:
[2020-07-14 17:50:26.610 CLI E] [!ERROR] Object reference not set to an instance of an object.
```

How can I answer yes to this in a non-interactive fashion?

**Comment by 2percentsilk** [comment]
Hey @TylerLeonhardt, there isn't currently a way to do this in a non-interactive fashion as far as I know.

Given the the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will need to be migrated to GitHub Codespaces. Since this migration isn't part of our roadmap and we're planning to retire the current self-hosted service on November 20, 2020, I'm going to close this as won't fix as we are not investing in this CLI anymore.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
