### ISSUE TITLE
My codespace never finishes starting

### ISSUE THREAD

**Issue by ppoffice** [MicrosoftDocs/vscodespaces#664]
The problem:

My codespace never finishes the start process after the previous suspension. Could this be an infrastructure failure or something wrong on my side since I have installed a lot of system packages recently?

BTW, it would be nice if there is some way for a user to export personal code/data from the codespace in the face of catastrophic failure.

Link:
https://online.visualstudio.com/environment/3edba63b-2e99-4252-b953-87c60441a010

**Comment by eljog** [comment]
Hi @ppoffice ,
Thank you for reporting this issue.
Upon primary investigation, it is observed that the resume attempt was failed due to a transient issue. We do also see that you were able to resume the environment successfully today around 11:54 pm UTC.
Please do reach out to us if you are still facing any issues.

We will be looking into action items to prevent transient issues such as this one.

Thanks,
Eljo

**Comment by danyhoron** [comment]
@eljog I'm encountering the same issue.
