### ISSUE TITLE
Port Forwarding Error

### ISSUE THREAD

**Issue by webstermath** [MicrosoftDocs/vscodespaces#665]
Port Forwarding has been working great with a React Firebase App I have been developing.  All of sudden and without any changes to the app,  when I click I go to the forwarded port, I get:

> You need to sign in first, redirecting...

It then sticks at a screen with the text:

>  Signing in...

In the console is the following warning

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://vortex.data.microsoft.com/collect/v1 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Did something change in chrome or vscodespaces? Is there a way to fix this?

**Comment by webstermath** [comment]
So, I was able to fix the issue above by opening codespaces in an incognito window.  Do multiple open Microsoft accounts interfere with port forwarding?

**Comment by sebastianrogers** [comment]
Getting this issue on multiple machines in different tenancies as of today.

**Comment by webstermath** [comment]
I just started having this issue again and I am only logged into one Microsoft account right now.

**Comment by webstermath** [comment]
Also, I just got the following new error in the console when loading the forwarded port:

> ReferenceError: define is not defined
    at VM1462 workbench.web.api.nls.js:4
(anonymous)	@	VM1462 workbench.web.api.nls.js:4

**Comment by webstermath** [comment]
I am now getting the following error when I try to access codespaces in Incognito:

> authService.ts:41 GET https://online.visualstudio.com/keychain-keys 401
m @ web.adda5874.chunk.js:1
init @ web.adda5874.chunk.js:1
Ie @ web.adda5874.chunk.js:1
async function (async)
Ie @ web.adda5874.chunk.js:1
(anonymous) @ web.adda5874.chunk.js:1
i @ runtime.280910aa.js:1
r @ runtime.280910aa.js:1
t @ runtime.280910aa.js:1
(anonymous) @ web.adda5874.chunk.js:1

**Comment by legomushroom** [comment]
@webstermath sorry for the trouble. Any of the errors you've posted does not seem to be related to the issue.

What browser are you using during the dev time? Chrome recently started blocking 3rd party cookies in incognito mode by default which indeed will interfere with our auth flow, you should see the crossed-eye icon in the URL bar on the right:

![image](https://user-images.githubusercontent.com/1478800/88005537-785a4400-cabe-11ea-949c-ae02b373c5dc.png)

Clicking on the icon and allowing 3rd party cookies should solve the issue. cc @klvnraju 

While I don't think Edge followed the same model yet, we saw some issues in the cases when you are logged in into the Edge browser account, try using a guest mode if you are using Edge. In any case, knowing more about your environment will help us to investigate the issue so please post your browser/machine info.

Also, if that happens can you try clearing out all cookies for the `online.visualstudio.com` domain and see if that helps? cc @plisy

**Comment by webstermath** [comment]
I am using Chrome.  I went ahead and cleared the cookies and it now works in non-Incognito mode.  Thank you for the advice.

**Comment by legomushroom** [comment]
@webstermath thanks for the update, @klvnraju any idea why cache can be the culprit here?

**Comment by sebastianrogers** [comment]
Also cleared cookies and its working for me.

**Comment by plisy** [comment]
@legomushroom I'm investigating right now, don't have the root cause yet.

**Comment by NiklasGustafsson** [comment]
I'm also seeing this. For me, clearing cookies doesn't seem to be working, but going 'InPrivate' in Edge does.

**Comment by plisy** [comment]
Can you try removing the service worker on the port forwarding domain?

**Comment by NiklasGustafsson** [comment]
@plisy: Do you mean stop the service (in this case my Flask server) that the port is forwarded to? That doesn't make any difference for me. If you mean something else, please explain.

**Comment by plisy** [comment]
There is a [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) running in the browser that creates the connection to the Codespace and exposes the service you're running inside only to your browser.

Right now, there's a bug that prevents this service worker to get authenticated properly once it's installed and active (handling requests for your port forwarding host). You can use your browser settings to clear the cookies and site data to remove this service worker. 

1. In setting search for "All cookies and site data" (works in Edge and Chrome)
1. Click on Cookies and site data (or Cookies and other site data in Chrome)
1. Find the site you need to clear (search by your codespace id - a guid you can take from codespace url)
1. Remove all the data for that domain. (e.g. 52af1948-b32f-415f-8084-218132853b91-3000.app.online.visualstudio.com)

Port forwarding should work after this until the Codespace gets suspended. Then you'll need to go through this exercise again until we release the fix for the bug.

**Comment by NiklasGustafsson** [comment]
@plisy:

Thanks, that takes care of it for me.

**Comment by plisy** [comment]
We deployed the fix for the issue.
