### ISSUE TITLE
Support self-hosting a remote container

### ISSUE THREAD

**Issue by 2percentsilk** [MicrosoftDocs/vscodespaces#666]
Filing an issue on behalf of @ntziolis based on an external conversation.

Scenario:

We use vscode + remote container feature to create dev containers on our own docker infrastructure
And would like to use codespace feature to be able to connect to them without requiring a vpn connection + todo shared coding sessions
We are absolutely be happy to pay for this way of using codespaces
I could imagine either packages (say up to x active codespaces x$ / month)
or by active codespace hour (could be minute but I think hour is acceptable and fair, day would not be. meaning active 5min pay for the day)
Why? Because we have a fairly beefy internal docker infrastructure and cannot justify paying for cloud hosted developer machines while we have this hardware running idle. Im sure we are not the only ones in this situation

I think there is a market for extending this further:

an agent to control the docker host that manages start/stopping of containers locally just like you provide for the cloud hosted containers + handling of code space registration

**Comment by ntziolis** [comment]
Adding a bit more thoughts why I think there is room from an entry level codespaces product especially looking at this from a business development + cloud / service adoption perspective :
- companies (especially but not limited to enterprise) do have their existing hw at least until refresh cycle hits
- offering them an entry level product like "management only" would be perfect to start to get them into container based development
  - what i mean with management only is an agent that sits locally that talks to a local docker server
  - the agent would handle the development container lifecyle (incl installing necessary agents to talk to code-spaces etc much like you are doing in your hosted product)
- you will gain insights into their usage patters over time
- allowing you to provide them with a customized cost / savings estimate vs buying new hw
  - as you know usage based cost is always a hard pill to swallow for customers if they cannot estimate how much usage they are going to have
- this might even come into play before hw refresh cycle if their internal demand rises
- by then they are already on the codespaces platform and its only a matter of choosing the resources (cloud vs their own) 
- this entry level sku would not be free but nowhere near as costly as paying for cloud compute resources, further reducing barrier of entry
   - obviously you could still offer a certain amount of environments for free like you do today
- entry level skus drive up customer numbers, which always is a good thing especially in this demographic since we all there are some key folks that care a lot about developer adoption of azure

Greetz from a former blue badge if you couldn't already tell from the above ;)
