### ISSUE TITLE
Clone the repository with the `codespace` user rather than root

### ISSUE THREAD

**Issue by saramarcondes** [MicrosoftDocs/vscodespaces#675]
Issue Type: <b>Bug</b>

Cloning the repository using `root` can cause common operations that are parts of npm package building to fail like `chmod` for example. This is super unexpected when opening a terminal into the codespace. Changing the repository cloning process to be done by the `codespace` user would fix this make the workspace behave just as though I had cloned it on my local machine in this regard.

I ran into this when running `yarn install` in https://github.com/Automattic/wp-calypso. It seemed to be breaking when `yarn` was linking binaries (https://docs.npmjs.com/files/package.json#bin). In this particular case, the `transpile` binary linked from `packages/calypso-build/bin` into `apps/full-site-editing/node_modules/.bin/transpile` was trying to be `chmod`ed and failing:

```error An unexpected error occurred: "EPERM: operation not permitted, chmod '/home/codespace/workspace/wp-calypso/apps/full-site-editing/node_modules/.bin/transpile'".```

The workaround was to `sudo chown codespace` on the actual file in the `calypso-build/bin` folder.

The steps to reproduce this are just to:
1. Create a codespace with Automattic/wp-calypso
2. Run `yarn install`

Extension version: 1.0.2526
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.3.0-1032-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (4.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: wp-calypso|
|OS|Linux x64 5.3.0-1032-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.75GB (0.46GB free)|
|VM|0%|
</details>

**Comment by jkeech** [comment]
@saramarcondes, thanks for reporting! This one might be tricky to solve generally, but would love if you have some ideas for how to improve this.

It's currently done this way as a perf optimization -- essentially, we have to clone the repo on the host VM in case you have a devcontainer.json file, which we need to inspect and then possibly build a Dockerfile from the repo. So we need access to the repo sources in order to build and run the container. The account used to run the clone is not guaranteed to be the same account as the one running inside the container.

In order to avoid cloning the repo twice (once to build the container, and then again inside the container), we bind-mount the repo from the host into the container. And in order to solve most permissions issues, we use ACLs to give read/write permissions to all users for that directory, so any user in the container has access to the repo directory. The main thing this doesn't solve is ownership. We intentionally do not `chown` the full contents recursively after finding out the container user because that is an expensive operation and we try to keep the creation as fast as possible.

Maybe we should do the clone on the host with a user account that has a specific `uid` that matches the `uid` of the default container user on the base image? That would at least fix ownership of the files for the default image when you don't use a `devcontainer.json`, but it would not fix ownership of the repo directory for custom images that run as a user with a different `uid`. Thoughts?

**Comment by jkeech** [comment]
I just tested `chown` on this repo (16k files in the directory, 341MB), and it actually doesn't slow things down too much: only 0.7s.

>codespace:~/workspace/wp-calypso$ time sudo chown -R codespace:codespace .
real    0m0.703s
user    0m0.023s
sys     0m0.126s

With that in mind, I think we can do a couple things:
1) For custom containers, continue cloning as `root` and then execute `chown` of the repo directory from inside the container using the `remoteUser` user, which is the same one that will be used to execute VS Code and tasks in the terminal. This will also allow us to get rid of the `chmod` and `setfacl` hacks that are in place on that directory to allow non-root users access to the files.
2) For the base image, perform the clone on the host with a user that has the same `uid` as the `codespace` user inside the base image, which is 1000. This will avoid having to change ownership after the initial clone that the custom container scenario needs.

Reference for `remoteUser`: https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/configuring#codespaces-configuration-reference

**Comment by Chuxel** [comment]
FYI - This was also reported for GitHub Codespaces here: https://github.community/t/running-yarn-leads-to-write-error/125935/4

**Comment by jkeech** [comment]
This change has been deployed! 🚀 All new Codespaces will have the workspace files owned by the `remoteUser`. I also ran a Codespace on the https://github.com/Automattic/wp-calypso repo, and ran `yarn install`, which succeeded.

![image](https://user-images.githubusercontent.com/746020/94187317-a19ba580-fe5c-11ea-82c4-4f7bebc6751f.png)
