### ISSUE TITLE
Port Forwarding is blocked by Safari pop-up restrictions

### ISSUE THREAD

**Issue by MarkLangford** [MicrosoftDocs/vscodespaces#728]
![2C0C00BF-8604-4F8F-B3FA-78682D26AAEF](https://user-images.githubusercontent.com/46607783/89778020-aef70d80-db04-11ea-94b5-a08c422fec01.png)
Is there a work around for accessing the port forward url? It does not copy to the clipboard and it does not open in another tab when selected.

**Comment by VincentDondain** [comment]
Hi @MarkLangford, unfortunately, there isn't a workaround at this time but we're looking into fixing this.

The copy&paste issue on iOS/iPadOS is here: https://github.com/MicrosoftDocs/vscodespaces/issues/616

**Comment by contention** [comment]
It would be great to get a fix or a workaround for this. Even if it’s a terminal command that exposes the port URL.

Apart from a few minor(ish) quirks with using Monaco on a touch device, this is probably the biggest blocker in terms of using a codespace on iPadOS.

Presume a fix for this will also filter through to GitHub codespaces, too?

**Comment by VincentDondain** [comment]
Rest assured we are working on this 😉 Yes anything we fix very much applies to GitHub Codespaces.

**Comment by contention** [comment]
@VincentDondain Thanks - that’s good to hear!

**Comment by contention** [comment]
Hey @VincentDondain - Is there an ETA for this fix? Or are issues being reported/discussed somewhere else now that Codespaces will be exclusively Github branded?

Thanks.

**Comment by VincentDondain** [comment]
No ETA unfortunately, we're looking at issues from a variety of place but this still is definitely a good place to track them (;

I'll keep you posted here for sure!

**Comment by lostintangent** [comment]
@contention Out of curiosity: what version of iPadOS are you running? I just tried this on the latest version (13.7), and when I click the port in the “Codespace Details” view (either view touch or using the magic keyboard trackpad), it opens the new tab as expected. 

I’m just wondering if this was a browser limitation that’s fixed in the latest iPadOS Safari or not.

As an aside, if it helps folks, you can run “npx codespaces-port <port>” from the integrated terminal, and that will print out the full URL that you could then open in a new tab.

**Comment by contention** [comment]
@lostintangent Argh, my bad. Safari was silently blocking pop ups. Apologies!

For the record I’m on iPadOS 14 Beta 7 right now.

**Comment by VincentDondain** [comment]
Hi, this is now fixed in the latest VSCode insiders build which will likely make it to Codespaces next week (:
