### ISSUE TITLE
STATUS_ACCESS_VIOLATION when switching back to tab

### ISSUE THREAD

**Issue by markjm** [MicrosoftDocs/vscodespaces#736]
Hi all -- I have been using Codespaces as my main driver for a few weeks now, and it is generally phenomenal!

Recently, however, I have been getting this access violation when going to a different tab (in same window) then tabbing back to codespaces tab. This is especially damaging when I have some command running and lose progress on that when I have to reconnect.

Specific repro steps:
1. Be on Edg/86.0.594.1
2. Load up into a workspace in one tab of a browser window
3. Navigate to a second tab in the same window
4. Sometimes, when navigating back to codespaces tab, see below error.

I see a few related issues online in the past few months, mainly for chrome ([example](https://geekermag.com/chrome-status-access-violation-error-code/)). I am currently on Edge Dev, so wondering if that is related. 

Here is my useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4210.0 Safari/537.36 Edg/86.0.594.1

![Capture](https://user-images.githubusercontent.com/16494982/89835377-875e7000-db19-11ea-9603-ec4623021521.JPG)

**Comment by srivatsn** [comment]
@legomushroom any thoughts?

**Comment by legomushroom** [comment]
We don't do anything special for the tabs change atm, so need time to investigate.

Looks like there is the same bug in Chrome Canary atm: https://bugs.chromium.org/p/chromium/issues/detail?id=1103104
Can you try more stable Edge? 

This post speaks about workarounds and the fix for Edge: https://www.chromestory.com/2020/05/status_access_violation/#:~:text=fix%20becomes%20available.-,status_access_violation%20%E2%80%93%20Microsoft%20Edge,we%20can%20try%20a%20workaround. The fix is bizzare - rename `msedge.exe` to something else, didn't test it though.

**Comment by markjm** [comment]
JFYI - this does not look to be affecting latest versions of Edge Dev
