### ISSUE TITLE
Codespace won't resume after idle self suspend

### ISSUE THREAD

**Issue by danyhoron** [MicrosoftDocs/vscodespaces#744]
In my codespace, I opened a custom workspace, and after 30 minutes it self suspended.
Now it won't resume. I had the same issue a while ago: #714 and @edgonmsft did some magic and it started.
My codespace is: https://online.visualstudio.com/environment/e001df0a-ebdf-4b72-bbb5-f54d4631ee55

Thank you.

**Comment by taiyosogawa** [comment]
@danyhoron, thank you for the report. We're taking a look at it now.

**Comment by kumarz** [comment]
@edgonmsft Is this because of the bad mount. What was the fix that you did for it to start in the beginning?

I see some unAuthorized compute exception that is causing it to shutdown
Then there was NullReferenceExceotion while starting it.
`
Authorized compute resource 'd2bb98dc-a269-4e88-94c4-05a29711401e' does not match target ''`

[Run](DefaultEvent
| where CloudEnvironmentId  == "e001df0a-ebdf-4b72-bbb5-f54d4631ee55" 
//| where level == "error"
| project-reorder ['time'], msg, level, CloudEnvironmentState, CloudEnvironmentOldState, CloudEnvironmentNewState, CloudEnvironmentNewUpdatedReason, CloudEnvironmentNewUpdatedTrigger, ErrorDetail, ErrorException, ErrorMessage
| limit 1000)


DefaultEvent
| where CloudEnvironmentId  == "e001df0a-ebdf-4b72-bbb5-f54d4631ee55" 
//| where level == "error"
| project-reorder ['time'], msg, level, CloudEnvironmentState, CloudEnvironmentOldState, CloudEnvironmentNewState, CloudEnvironmentNewUpdatedReason, CloudEnvironmentNewUpdatedTrigger, ErrorDetail, ErrorException, ErrorMessage
| limit 1000

**Comment by danyhoron** [comment]
@taiyosogawa any news? It's almost 2 weeks since it stopped working.

Thanks.

**Comment by taiyosogawa** [comment]
@kumarz, would you be able to take a look into this?

**Comment by kumarz** [comment]
> @kumarz, would you be able to take a look into this?

yeah sure, getting some release stuffs in line and will work on this right away.

**Comment by kumarz** [comment]
@danyhoron Can you please give a shot to shutdown and restart the codespace, we recently found out it works for a user after our recent production deployment.

**Comment by danyhoron** [comment]
@kumarz I just tried with no luck.
It still won't start.

**Comment by kumarz** [comment]
> @kumarz I just tried with no luck.
> It still won't start.

Thanks for checking, we are going to check the storage of this codespace & fix it, if needed and keep you posted.

**Comment by danyhoron** [comment]
@kumarz is there any chance you could clone my storage and create a new codespace and attach it the cloned storage?

**Comment by kumarz** [comment]
> @kumarz is there any chance you could clone my storage and create a new codespace and attach it to the cloned storage?

yes, we are going to fix the storage and take back up of the files and let you know to give it a shot. I will keep you posted.

**Comment by GideonCheruiyot** [comment]
Hi @danyhoron , we have backed up the files in your workspace. Could you try resuming your codespace again?

**Comment by danyhoron** [comment]
@GideonCheruiyot I just tried. It and behavior. It won't resume.

**Comment by GideonCheruiyot** [comment]
Sorry for the inconvenience @danyhoron , we will keep investigating to find the root cause.  To get you unblocked, it might be nice to export your files then create a new codespace if you would like. how would you like us to provide the files in your workspace? Would you like us to send a download link in the email in your git config, or do you have a different email we could send it to? You could also provide us with a GPG public key and we can encrypt the download link using the GPG key and post it here.

**Comment by danyhoron** [comment]
@GideonCheruiyot Here's my gpg public key.
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF49incBCAC9lzVrK3J9Kr/0reljSqaS3a05UJJrI9YC0UXEJzIdS8DRj/xk
qyv/bAZLXVjsGgsHD3YpOA77WhqkC3SuccDjAsZHQqEmuwIxijf3B5X+nBg2EkCT
5e8qaAks1Jo9kCrxzZyQxdOfcWPWmgFBSbvueHwvxmUsGy+MAaC/OSGVwh2OQGWj
jc7u3QoFGlXv1V9tTKhE5V1kbdc4yk6YqqaYM4i9WSaWRDdHqXiDQ6rXnIDkhq11
aQDwAa9aYMfL6DwsFpLbaE4CwRdwGDiPUxhq7hTNgQLH4rNQNCQfW3T2Dndoxrr6
tkO3YP9d+Xi+QX5wx7xNW7lFxQO7jnkzN9ftABEBAAG0GkRhbmkgSG9yb24gPGRh
bmlAaG9yb24ucm8+iQFUBBMBCAA+FiEECvCse0W0Sch3/X7lnwICJ8i19MEFAl49
incCGwMFCQPCZwAFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQnwICJ8i19MFE
Ngf/eXViCLd+x+U7jHSUwdGm06ENlVKGPVj1iEqd/DTEoGBSxGOb7ptRlGlpv2p4
Qqt8vKI0RJ0GoUDDBDRLUGfW8RxNvutprzeEwwbzd4qE5eblvYM5AbgXsBBqwj0E
lcxICOIPwTQ+D4AzmmImikcwIJThO/hBN0ymkjJY9ER+FREIcfAEnakqULLnx8WA
TSj4HdMORZ4rH0h2KVA/IvTXO4LL5tm38Khq0e8eLY3Yp89rkHHMd4eGxSBSpXWb
Guqzcdr72GZ1F5QHVFykZwCmg8OsoBcljwQiTXAHcHVvDpw/gW77N02dnhD4ckIn
pvqTOpWv4vAtWx50RPsXRjhILLkBDQRePYp3AQgA2iEQraohvbVw80u1RBHuE5wm
2nI77md5cebVcNerXsf1lyOfL8LNIXiqT0SbvQAQK6Z0aSXVhu/0btp0nL1XH0/I
yprDIiiaumvJXiS1ufwodOMFZ46M/4hyHu0mQO8v19G4IcxmqQ7MWgEyYeqqZmgC
JojsGQ+uvmRr7bsHnnSCcMYwcKyC8vEdsLY4GKB+bYR/tXccF5TITmFnfHntVn35
6TYj723xLfnsOVsJMGDFDkw9BuWsgFt2joLVwVtduaIdnOVjzywIK/6cyXeP1t04
px4qj/V/emGCgAzhCAqfaiqeO6C4uZGCy6dluAXsXm23SX841D0kO+JSa3YPMwAR
AQABiQE8BBgBCAAmFiEECvCse0W0Sch3/X7lnwICJ8i19MEFAl49incCGwwFCQPC
ZwAACgkQnwICJ8i19MFJ1wf/V/hu99RmMir+0O5ta833SP1xcFKPfiwB8x92ZMR7
kAnXLK7WetRALFWWHWjpJFxBgpGh6YIWqxGwCTqak8I8BH9om6qgx1t0L6O1sakb
BZfeCdJr9CQniJ/j7X0LvVlA4Ws4CRn8O2THGGR2olcO/vwAUM3Kef9KIvcV9u8s
YX3SIr6YqknD0dy8u4Ic4PHttHyL1fO+U4kwddSdB0rpfh+3/jnvRyiPfKttfD7r
yhY4JSMlEVScF1isBzPTv8iljyF4mBzJaPH+QLdc6KdazMrrYnOcSjkkMipP4GcE
RfPssEiNsklmvWW5TKaCperbCZFGd2WryPe32Jl4AMkuqQ==
=I1w3
-----END PGP PUBLIC KEY BLOCK-----
```
Please encrypt it and send the link to my email address in the git config file.
Can you please include `.ssh` and `.aws` folders?

Thank you.

**Comment by jkeech** [comment]
@danyhoron, we sent you an email with an encrypted download link. Let us know if you have any issues. Thanks!
