### ISSUE TITLE
Clone from private Bitbucket repo

### ISSUE THREAD

**Issue by rlimberger** [MicrosoftDocs/vscodespaces#754]
It is currently not possible to create a Codespaces from a private Bitbucket repo in the portal nor with the CLI. This is probably due to lack of login credential or access token options. I would like to request this be added. Thank you.

**Comment by kumarz** [comment]
Thanks for bringing this up, We will have this tracked as a feature request.

**Comment by lostintangent** [comment]
Using the terminal, users can clone repos from any code host, and authenticate from the CLI just like they would locally. Is that not working for you? Since this isn't blocked, I'm going to close this as resolved. If you'd like to see us add a more integrated experience, please file an issue on our [Community Support](https://github.community/c/codespaces-beta/45) forum, which is where we're discussing roadmap items for the consolidated GitHub Codespaces experience. Thanks!
