### ISSUE TITLE
Document codespace cli versions and changelog

### ISSUE THREAD

**Issue by mJehanno** [MicrosoftDocs/vscodespaces#771]
Hey,

I was checking the codespace cli documentation and as I'm trying to use the self-hosted process, I saw that there was (or could find) no trace of the current version of the codespace cli, nor the previous versions.

For exemple, I'm waiting for #720 to be solved and I assume that you'll do a fix/patch etc ... but it won't be specially clear in the documentation that you made an improvement on the codespace cli, it might just be told as a comment in this issue.

**Comment by 2percentsilk** [comment]
Thanks for the feedback!

It sounds like a sort of changelog with addressed issue numbers might solve this for you. What do you think about that?

**Comment by mJehanno** [comment]
It would be great !

**Comment by lostintangent** [comment]
As part of consolidating Codespaces into GitHub Codespaces, we'll need to migrate support for self-hosted Codespaces over to the GitHub-native experience. This isn't currently on our roadmap, and so I'm going to close this issue as won't fix, since we're not going to be investing in the new CLI moving forward. If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on [this issue](https://github.community/t/self-hosted-codespaces/131361/17). Thanks!
