### ISSUE TITLE
Recent periodic hiccups with Codespaces

### ISSUE THREAD

**Issue by MSFTJim** [MicrosoftDocs/vscodespaces#781]
This week (maybe longer) I have noticed various hiccups when either creating or using Codespaces.  Waiting a timeout period and then refreshing seem to solve the issue but this was not the experience I had been seeing previously.

Working with another who was experiencing similar, so it was not limited to just my Codespaces.  

![CSerr1](https://user-images.githubusercontent.com/33520581/92030038-7548a980-ed34-11ea-80e8-e773f08b86a9.png)
![CSerr2](https://user-images.githubusercontent.com/33520581/92030042-75e14000-ed34-11ea-8387-ab53a971dcaf.png)

**Comment by timrobertsusa** [comment]
i am going thru LONG waits -- and this is very inefficient and would appreciate addressing this.

**Comment by lostintangent** [comment]
@jkeech Any thoughts here? I know we've been addressing a lot of reliability/connectivity issues, and so maybe this has been addressed?

**Comment by jkeech** [comment]
Creation time is something we are continuing to work to speed up. The "Request is not defined" issue was also recently fixed in last week's extension deployment (related to https://github.com/MicrosoftDocs/vscodespaces/issues/567). That error would only show up if using some other specific extensions, like the Azure Pipelines extension, but it should be fixed now.

I'm going to go ahead and close this issue, but feel free to re-open if you are continuing to see issues. Thanks!
