### ISSUE TITLE
No support for nested virtualization

### ISSUE THREAD

**Issue by Rishit-dagli** [MicrosoftDocs/vscodespaces#792]
Issue Type: **Bug**

As of now, there seems to be no support for enabling nested virtualization for [GitHub Codespaces](https://github.com/codespaces). I understand that due to various reasons cloud VMs would have nested virtualization switched off by default but this would most widely be helpful while Android/ IoS development where these capabilities could help. It would be great if there could be an option to toggle this or allow us to add licenses while VM creation (as shown below).

I earlier experimented with nested virtualization especially for Android/ IoS development on another cloud provider (GCP) and have published my and @preetjdp findings [here](https://medium.com/@rishit.dagli/set-up-a-android-development-environment-in-gcp-15ca742b63be). The major part which allowed Nested Virtualization was adding a license while VM creation (I also believe that this might be the easiest way to do so) -

```sh
--licenses "https://compute.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"
```
 
Maybe a similar approach could be used to facilitate this or allow the developers to add the licenses in a Codespace.

**Comment by jkeech** [comment]
@Rishit-dagli, the VMs that the Codespaces run in do support nested virtualization, but since the Codespace runs in a docker container on the VM, the container sandboxing is likely not allowing this scenario to work. We will need to do some investigation to see how we can expose nested VM functionality from within the container.

That said, the nested VM would likely not be persisted across Codespace suspend/resume cycles, since the underlying VM is discarded. So when the container restarts on a new VM when you come back after a period of inactivity, you'd need to spin up another VM for the emulator.

**Comment by lostintangent** [comment]
@Rishit-dagli Hey! As we discussed in #790, would you be able to port this discussion to the [GitHub Support Community](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/)? We'll be transitioning our feature requests/roadmap items to that, and so it would be great to keep the conversation going from there. Thanks so much!

**Comment by Rishit-dagli** [comment]
> @Rishit-dagli Hey! As we discussed in #790, would you be able to port this discussion to the [GitHub Support Community](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/)? We'll be transitioning our feature requests/roadmap items to that forum, and so it would be great to keep the conversation going from there. Thanks so much!

Sure! I can do the same for this issue too.
