### ISSUE TITLE
"Activating extension 'ms-vsonline.vsonline' failed" when running extension tests with a custom --user-data-dir

### ISSUE THREAD

**Issue by DanTup** [MicrosoftDocs/vscodespaces#801]
I see this error anytime I run my extension's tests in the extension host:

> Activating extension 'ms-vsonline.vsonline' failed: ENOENT: no such file or directory, mkdir '/Users/danny/Dev/Dart-Code/.dart_code_test_data_dir/User/globalStorage/ms-vsonline.vsonline'.

![Screenshot 2020-09-17 at 08 52 51](https://user-images.githubusercontent.com/1078012/93437179-93311500-f8c3-11ea-867b-721cf92c9484.png)

I pass a custom `--user-data-dir` when running tests so that the tests aren't influenced by my own VS Code User Settings etc.

(moved from https://github.com/microsoft/vscode/issues/106921)

**Comment by jkeech** [comment]
@DanTup, thanks for reporting. This does look like a bug in our extension.

**Comment by jkeech** [comment]
I'm not able to reproduce this error on my machine, because it looks like a race condition where VS Code typically creates the parent globalStorage directory before the extension activates, but if the extension activates before that directory is created, it doesn't recursively create the directory structure, so this error would occur. The fix is to change the directory creation for our extension's global storage path to recursively create the directory structure instead of depending on VS Code to create the parent directories.

Our next extension release should include this fix.

**Comment by jkeech** [comment]
The updated extension with this fix is now live on the marketplace. Let us know if you continue to see these issues after updating to the latest version. Thanks!
