### ISSUE TITLE
Switch dotfiles installation to before the postCreateCommand

### ISSUE THREAD

**Issue by felipecrs** [MicrosoftDocs/vscodespaces#811]
The dotfiles installation is happening currently **after** the `postCreateCommand`. This is wrong because the workspace/project/repository preferences must take precedence over the user's preferences, just like how the priority order for the VSCode's `settings.json` is managed.

**Note:** the Remote - Containers extension does not have this issue.

**Comment by lostintangent** [comment]
This seems to make sense to me. @jkeech @Chuxel Thoughts?

**Comment by jkeech** [comment]
@felipecrs, @lostintangent, the reason we run all personalization steps after the customization steps is because repo-level customization steps need to be applied deterministically. Personal dotfiles can define aliases or modify the PATH or many other things that would break or alter the behavior of the customization scripts that are present in the repo, which would be hard (and in some cases impossible) for the repo owner to anticipate and account for.

We run all customization steps first so that the postCreateCommand will succeed for all users as long as it succeeds for one of them. At the end of the script execution, all Codespaces created from that commit should be functionally equivalent. After that point, we apply personalizations which can conditionally override or tweak things as needed based on personal preference.

The difference in the VS Code settings case is that settings can be merged cleanly in any order, but that isn’t guaranteed to be true for the script executions.

In most cases though, postCreateCommand should not interfere with dotfiles. PostCreateCommand typically operates within the repo workspace directory (package restore, build, etc). Dotfiles typically alters things at the HOME directory level (user-wide). PostCreateCommands that do not depend on repo state and set things up globally or user-wide should ideally be moved into the image itself.

**Comment by felipecrs** [comment]
@jkeech I still disagree. I believe that the workspace customization MUST take precedence over the user customization, to assure not a working development environment, but one equal to the rest of the team.

Nonetheless, what about my statement regarding the _Remote - Containers_ extension? Should it be changed there? I believe both extensions should behave similarly since they are essentially the same thing: one for local, the other for the cloud.

**Comment by jkeech** [comment]
> I believe that the workspace customization MUST take precedence over the user customization, to assure not a working development environment, but one equal to the rest of the team.

I'm not sure I'm following the equality statement. Injecting dotfiles into the middle of the workflow would not result in an equal or identical output. Applying dotfiles at the end results in a more deterministic outcome because the environments will only diverge after the `postCreateCommand` is finished. In stead of interleaving repo -> user -> repo, it's just repo -> user. Interleaving is what causes the problems since all of the repo-provided scripts that would execute after the user dotfiles runs could be impacted.

Another way to think about it: Dotfiles, by definition of being user-level personalizations, must be able to be applied on top of any repo that a user uses. So dotfiles already need to be authored to work well with other repos. On the other hand, repo-defined `postCreateCommand` and any other scripts should not be required to compensate for arbitrary dotfiles modifications of end users. Applying personalizations after customizations is the best solution for repo maintainers because they can be sure that all users start from the same place and have less "it works on my machine" problems during the `postCreateCommand`.

But just because dotfiles install runs second does not mean that personalizations must override repo-provided config though. In the rare cases where there would be collisions, the dotfiles install script can be updated to have whatever behavior you want -- either override the repo default or not override the repo default depending on the situation and your desired behavior.

> what about my statement regarding the _Remote - Containers_ extension? Should it be changed there? I believe both extensions should behave similarly since they are essentially the same thing: one for local, the other for the cloud.

I agree. I wasn't aware of the ordering in the Remote Containers extension today, but it should behave the same. cc @chuxel, @chrmarti

**Comment by chrmarti** [comment]
Remote-Containers uses the following sequence:
- Install dotfiles.
- Setup configuration to connect to the outside:
  - Copy local `~/.gitconfig` and `~/.ssh/known_hosts` to the container _if they not already exist_.
  - Set up a forwarding Git credential provider in the `.gitconfig`
- Run `postCreateCommand`.

This way `postCreateCommand` can use Git and SSH with (parts of) the user's configuration. Any existing `.gitconfig` is not overwritten, so currently a `.gitconfig` from the dotfiles repo wins. Deferring the dotfiles install to after `postCreateCommand` would remove that flexibility.

**Comment by felipecrs** [comment]
Example:

Let's say your development environment wants to use a specific version of `node`, so in `postCreateCommand` you do something like `nvm alias default 11`.

However, the user also has a `node` version of their preference ([as I do](https://github.com/felipecrs/dotfiles/blob/master/run_once_setup.sh#L165)), so in the dotfiles installation, the user changes the default `node` version: `nvm alias default 12`.

This will cause the "it works on my machine" problem.

**Comment by jkeech** [comment]
> Let's say your development environment wants to use a specific version of `node`, so in `postCreateCommand` you do something like `nvm alias default 11` (I know that you can also do it in the Dockerfile).
> 
> However, the user also has a `node` version of their preference ([as I do](https://github.com/felipecrs/dotfiles/blob/master/run_once_setup.sh#L165)), so in the dotfiles installation, the user changes the default `node` version: `nvm alias default 12`.

Hey @felipecrs, thanks for the continued discussion. It's certainly possible to come up with situations where you would prefer either ordering. The main challenge is to pick the best ordering for the majority of scenarios and users. This scenario is an interesting one to drill into.

In Codespaces, we have two concepts for tweaking the config: _customization_ and _personalization_:

### Customization ###
Customization is the ability to tweak the environment for a specific project which primarily includes installed toolsets for building/running/testing the app which should be the same for every developer. Custom container configuration and `postCreateCommand` are common examples of customization hooks. 

In short, **customizations are for functional behavior**. Customization should not include things that are based on personal preference, but instead should include things related to the technology stack used to build the application.

### Personalization ###
Personalization is the ability to tweak the editor and terminal based on your personal preferences. Personalization choices are tied to the user and span all repos/Codespaces that a user creates. This includes things like VS Code themes, VS Code keybindings, terminal themes, terminal aliases, etc. Personalizations are applied via `dotfiles` repos and VS Code  settings sync.

In short, **personalizations are for non-functional preferences**. Personalizations should not be making technology decisions for applications such as changing node engine versions, installing different compiler/runtime versions, etc. Technology decisions should be encoded as customizations in the repo so they are shared across all developers.

### Summary ###
If you follow the pattern of separating customizations from personalizations, then Codespaces will work much better for you and anyone else who uses your repos. Everything needed to run your app would be specified as customizations and shared with everyone, giving a functionally equivalent environment to every Codespace. Everything else tied to the way you like to interact with your editor is applied consistently to all of your Codespaces, but that will not change the functional behavior of your applications.

Regarding order of application, applying personalizations after customizations is the proper order in my opinion, due to the reasons outlined previously: Personalizations should never interfere with how the Codespace environment is spun up. They should apply cleanly on top of any repo. On the flip side, Codespaces should also always be able to be created without any personalizations defined at all. If you encounter a situation where you require something from your dotfiles in order to create a working Codespace for a repo, then that means the repo is missing something that should be defined as a customization and shared with everyone else for a consistent environment.

**Comment by felipecrs** [comment]
@jkeech Thanks for the elaborated explanation.

> Regarding order of application, applying personalizations after customizations is the proper order in my opinion, due to the reasons outlined previously: Personalizations should never interfere with how the Codespace environment is spun up.

Do you have any example to illustrate a possible problem of applying the dotfiles before the postCreateCommand? It's being this way in Remote - Containers which I use extensively and I never had a problem. I suppose the Remote - Containers guys also did not hear about any problem.

> On the flip side, Codespaces should also always be able to be created without any personalizations defined at all. 

For sure, this must be 95% of the cases actually. It's even true for Remote - Containers, so I guess this has nothing to do with the order. No matter what, the repository must not depend on the dotfiles.

**Comment by chrmarti** [comment]
@jkeech Another type of configuration is for enabling outside connections (connection configuration) like authentication (e.g., Git credentials helper) and networking (e.g., proxy settings). Connection configuration can be personal or machine specific. The reason I chose to install dotfiles before running `postCreateCommand` is that dotfiles can contribute to the connection configuration and `postCreateCommand` can then depend it. E.g, https://github.com/microsoft/vscode-remote-release/issues/1980 discusses checking out a private Git repository in `postCreateCommand`.

I agree personalization is best applied at the end and should not be required to setup a local DevContainer, for connection configuration on the other hand this does not hold, instead it needs to be added early, so customization can depend on it.

Not sure what the Codespaces view is on this. At which point are you registering a Git credentials helper?

**Comment by jkeech** [comment]
@chrmarti and I discussed this a bit, and we came to the conclusion that executing dotfiles after the `postCreateCommand` is the right approach. He is going to think though how the credential helper and other secrets can be run earlier in the process for Remote Containers to provide consistency across both experiences.

I'm going to go ahead and close this issue relating to Codespaces as Won't Fix since the current ordering in Codespaces matches the ordering we want. There will likely be a separate issue filed for Remote Containers to change the order after the details are worked though. Thanks!

**Comment by felipecrs** [comment]
@jkeech thanks for the clarifications.

Just for the record, the [issue example I demonstrated](https://github.com/MicrosoftDocs/vscodespaces/issues/811#issuecomment-708009678) is not covered by the current solution. It was never a real issue, so I hope we don't face that.

**Comment by jkeech** [comment]
> Just for the record, the [issue example I demonstrated](https://github.com/MicrosoftDocs/vscodespaces/issues/811#issuecomment-708009678) is not covered by the current solution. It was never a real issue, so I hope we don't face that in real life.

@felipecrs, That is an example that goes against the customization/personalization split where dotfiles should not be making technology decisions -- those should be encoded in the app repo's devcontainer environment. From the comment above https://github.com/MicrosoftDocs/vscodespaces/issues/811#issuecomment-709537005:

>In short, personalizations are for non-functional preferences. Personalizations should not be making technology decisions for applications such as changing node engine versions, installing different compiler/runtime versions, etc. Technology decisions should be encoded as customizations in the repo so they are shared across all developers.

**Comment by felipecrs** [comment]
It makes sense. I think this should be documented in:

https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/personalizing-codespaces-for-your-account
