### ISSUE TITLE
Is there a way to remove or disable the GitHub link at the top??

### ISSUE THREAD

**Issue by ChayimFriedman2** [MicrosoftDocs/vscodespaces#813]
Every time I want to visit files explorer, out of habit I click the topmost button in the title. Unfortunately, in GitHub Codespaces this button is instead "Go Home":
![image](https://user-images.githubusercontent.com/24700207/94556478-d006ef80-0265-11eb-9d96-8cfc96c74229.png)
Now, this is really frustrating, because I lose my context every time. And the button isn't even draggable like the others! Is there any way to get rid of it?

**Comment by 2percentsilk** [comment]
Unfortunately, there isn't a way to disable or remove the GitHub tile in the top corner at this time.

I'm going to close this issue since your request pertains to GitHub Codespaces and feature requests and roadmap updates for the future live at https://github.community/c/codespaces-beta/45. Please feel free to file this request on the Community site as we'll be using feedback like this as we polish our user interactions in Codespaces.

**Comment by bpasero** [comment]
You can hide the "Home" button from the right click menu:

![image](https://user-images.githubusercontent.com/900690/94777945-9dbfd400-03c4-11eb-966a-e5e48bf19e97.png)
