### ISSUE TITLE
Error message: Failed to connect to relay

### ISSUE THREAD

**Issue by avdev4j** [MicrosoftDocs/vscodespaces#828]
**Describe the bug**
I am a part of the beta testing phase of GitHub Codespace and I'm not able to start a Codespace session due to an error "Failed to connect to relay".

**To Reproduce**
1. Go to one of my repository
2. Create a new codeSpace
3. When the codeSpace is available the error message appear in the right corner
![Capture d’écran 2020-10-28 à 14 12 42](https://user-images.githubusercontent.com/37835668/97451562-25e9b880-1934-11eb-86f0-2ccb75dc8d29.png)
4. Finally, no action, editing code is possible.

**Expected behavior**
Nothing special than be able to code with GitHub codespace.

**Screenshots**

**More details (please complete the following information):**
- Codespace Instance Type: ?
- Client: GitHub CodeSpace
- OS Version: macOs Catalina 10.15.7
- Browser: Chrome 86.0.4240.111 and Safari 14.0 (15610.1.28.1.9, 15610)
- Tested with two different internet providers
- Tested on laptop and smartphone

Brower-based editor details:
- Browser [e.g. chrome, safari]: Chrome
- Version [e.g. 22]: 86.0.4240.111

- Browser [e.g. chrome, safari]: Safari 
- Version [e.g. 22]: 14.0 (15610.1.28.1.9, 15610)

**Additional context**
Related to https://github.com/microsoft/vscode/issues/109602 
Since I wrote the issue, the bug disappeared.

**Comment by jkeech** [comment]
There was a new CSP rule deployed yesterday for added security, but it missed one of the relay endpoints in the West Europe region, so access to Codespaces in West Europe from the web browser were blocked due to the CSP rule. We rolled out a service fix this morning with an updated CSP rule, so you should be able to connect now. Please re-open if you continue to see issues. Thanks!

**Comment by avdev4j** [comment]
Good to know, thank you for the information!
