### ISSUE TITLE
Codespace not started

### ISSUE THREAD

**Issue by torkel** [MicrosoftDocs/vscodespaces#844]
My codespace is not starting
https://online.visualstudio.com/environment/c21ba3fe-6d32-445e-a8b2-f05245645ff8

Trying to start from Visual Code and from browser
(https://online.visualstudio.com)

Trying to start but after a while it goes back to suspended.

**Comment by jkeech** [comment]
@torkel, thanks for reporting. We're aware of an issue with resumes affecting empty codespaces (codespaces not created from a repo). We're working on a fix. This only impacts Visual Studio Codespaces and not GitHub Codespaces.

**Comment by jkeech** [comment]
The fix for this issue has been deployed. You should be able to resume the codespace now. Closing this issue, but let us know if you continue to see issues resuming.

Note that Visual Studio Codespaces is deprecated, and new codespaces are not officially supported anymore. Creation of Visual Studio Codespaces will be blocked very soon, and all existing Visual Studio Codespaces will be deleted on February 17, 2021 as outlined in this issue: https://github.com/MicrosoftDocs/vscodespaces/issues/788. Please migrate your data off of your Visual Studio Codespace as soon as possible.

We hope to see you on [GitHub Codespaces](https://github.com/features/codespaces) in the future. Thanks!
